### PR TITLE
 Python 3 and Python 2

### PR DESCRIPTION
**Pull request by danhamill**
Mike,

This is a great package.  In the spirit of collaboration, please consider this pull request.  

#changes 
Added compatibility for python 3.6.  
Also tested for compatibility with python 2.7 and everything seems to work.

To get the install to work properly with Anaconda, I had to change the parserasgeo imports to relative imports.  Seems like a windows issue, but hopefully it will still work on your end.

Tested on:
conda version: 4.6.3
conda-build version: 3.10.5
python version : 3.6.5.final.0
python version: 2.7.15

If this doesn't work, or want to merge somewhere on another branch let me know.  

Thanks,

Dan

### CODE REVIEW

**Comment by mikebannis** [comment]
Dan, I'm glad you found prg to be useful and thanks for the help! I've been meaning to upgrade it to python 3 but haven't had time.  Give me a couple days to look at it and I'll get back to you.

**Comment by mikebannis** [comment]
Dan, the python 2->3 compatibility stuff looks like only three things changed:

- Added () to print statements
- made relative imports explicit
- removed white space

Is that correct? Did anything else change? Thanks!

**Comment by danhamill** [comment]
That's correct.  Based on my tests, everything else appears to be compatible.  It's a well-designed package and didn't have any external library issues.  

I installed it  using:

```
python setup.py install
```

The install went fine, but when I tried:

```
import parserasgeo as prg
```

the imports failed.  See my generic [SO post](https://stackoverflow.com/questions/55130909/install-and-load-module-with-embeded-init-py-files).

**Comment by mikebannis** [comment]
tested on my end and works in python 2.7 :shipit:

**Pull request merged**
